// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {plugins} from '../models';
import {games} from '../models';
import {scripting} from '../models';

export function GetAvailablePlugins():Promise<Array<plugins.PluginRepositoryInfo>>;

export function GetInstalledGames():Promise<Array<games.Game>>;

export function GetInstalledPlugins():Promise<Array<scripting.LuaPlugin>>;

export function GetPluginRepositories():Promise<Array<plugins.PluginRepository>>;
