// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAvailablePlugins() {
  return window['go']['main']['App']['GetAvailablePlugins']();
}

export function GetInstalledGames() {
  return window['go']['main']['App']['GetInstalledGames']();
}

export function GetInstalledPlugins() {
  return window['go']['main']['App']['GetInstalledPlugins']();
}

export function GetPluginRepositories() {
  return window['go']['main']['App']['GetPluginRepositories']();
}
